name: Build VSIX Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Setup Yarn
        run: npm install -g yarn@1.22.22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build VSIX package
        run: yarn package

      - name: Upload VSIX package
        uses: actions/upload-artifact@v7
        with:
          name: theme-extension
          path: "*.vsix"
          retention-days: 14

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
          generate_release_notes: true
